Build multi-platform images
Build images for both amd64 and arm64. Build images on release
rather than on tags, and support `t/*` tags.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -18,10 +18,11 @@ env:
       - "dependabot/**"
       - "gh-readonly-queue/**"
       - "renovate/**"
+      - "t/**"
       - "tickets/**"
       - "u/**"
-    tags:
-      - "*"
+  release:
+    types: [published]
 
 jobs:
   test:
@@ -45,9 +46,11 @@ jobs:
         run: uv run --only-group=tox tox run -e lint,typing,py,coverage-report
 
   build:
-    runs-on: ubuntu-latest
     needs: [test]
-    timeout-minutes: 15
+    uses: lsst-sqre/multiplatform-build-and-push/.github/workflows/build.yaml@v2
+    secrets: inherit
+    with:
+      images: ghcr.io/${{ github.repository }}
 
     # Only do Docker builds of tagged releases and pull requests from ticket
     # branches. This will still trigger on pull requests from untrusted
@@ -55,32 +58,26 @@ jobs:
     # but in this case the build will fail with an error since the secret
     # won't be set.
     if: >
-      github.event_name != 'merge_group'
-      && (startsWith(github.ref, 'refs/tags/')
-          || startsWith(github.head_ref, 'tickets/'))
+      (github.event_name == 'release' && github.event.action == 'published')
+      || (github.event_name != 'merge_group'
+          && (startsWith(github.head_ref, 'tickets/')
+              || startsWith(github.head_ref, 't/')))
 
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          fetch-depth: 0
+  build-worker:
+    needs: [test]
+    uses: lsst-sqre/multiplatform-build-and-push/.github/workflows/build.yaml@v2
+    secrets: inherit
+    with:
+      dockerfile: Dockerfile.worker
+      images: ghcr.io/${{ github.repository }}-worker
 
-      - uses: lsst-sqre/build-and-push-to-ghcr@v1
-        id: build
-        with:
-          image: ${{ github.repository }}
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Report result
-        run: |
-          echo Pushed ghcr.io/${{ github.repository }}:${{ steps.build.outputs.tag }}
-
-      - uses: lsst-sqre/build-and-push-to-ghcr@v1
-        id: build-worker
-        with:
-          dockerfile: Dockerfile.worker
-          image: ${{ github.repository }}-worker
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Report result
-        run: |
-          echo Pushed ghcr.io/${{ github.repository }}-worker:${{ steps.build-worker.outputs.tag }}
+    # Only do Docker builds of tagged releases and pull requests from ticket
+    # branches. This will still trigger on pull requests from untrusted
+    # repositories whose branch names match our tickets/* branch convention,
+    # but in this case the build will fail with an error since the secret
+    # won't be set.
+    if: >
+      (github.event_name == 'release' && github.event.action == 'published')
+      || (github.event_name != 'merge_group'
+          && (startsWith(github.head_ref, 'tickets/')
+              || startsWith(github.head_ref, 't/')))
